/*
 * CamSub.h
 *
 *  Created on: Mar 24, 2017
 *      Author: Robot Mafia
 */

#ifndef CAMSUB_H_
#define CAMSUB_H_

#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class CamSub: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Servo> bottomServo_Motor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	CamSub();
	void InitDefaultCommand();
	void CamTurn(double degrees);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};




#endif /* CAMSUB_H_ */
