/*
 * CamCom.h
 *
 *  Created on: Mar 24, 2017
 *      Author: Robot Mafia
 */

#ifndef CAMCOM_H_
#define CAMCOM_H_

#include "Commands/Subsystem.h"
#include "../Robot.h"




/**
 *
 *
 * @author ExampleAuthor
 */
class CamCom: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	CamCom();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
	bool DPadLeft;
	bool DPadRight;


	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};




#endif /* CAMCOM_H_ */
