// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveCom.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveCom::DriveCom(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveSub.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	XAxis = 0;
	YAxis = 0;
	RotAxis = 0;
	XButton = false;
	HalfFlag=false;
	YButton=false;
	RevDrive=false;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveCom::Initialize() {
XButton=false;
HalfFlag=false;
YButton=false;
RevDrive=false;
}

// Called repeatedly when this Command is scheduled to run
void DriveCom::Execute() {
	RotAxis = Robot::oi->getDriverJoystick()->GetRawAxis(0);
	XAxis = Robot::oi->getDriverJoystick()->GetRawAxis(1);//these are for Xbox 360 controller
	YAxis = Robot::oi->getDriverJoystick()->GetRawAxis(4);
	XButton = Robot::oi->getDriverJoystick()->GetRawButton(3);
	YButton = Robot::oi->getDriverJoystick()->GetRawButton(4);

		if(XAxis > -0.20 && XAxis < 0.20)
		{
			XAxis = 0;
		}
		else
		{
			XAxis = XAxis * fabs(XAxis);
		}
		if(YAxis > -0.20 && YAxis < 0.20)
		{
			YAxis = 0;
		}
		else
		{
			YAxis = YAxis * fabs(YAxis);
		}
		if(RotAxis > -0.20 && RotAxis < 0.20)
		{
			RotAxis = 0;
		}
		else
		{
			RotAxis = RotAxis * fabs(RotAxis);
		}



		if(XButton){//XBUTTON IF

			if(HalfFlag == false){//HALFFLAG F IFdrive full speed
				HalfFlag = true;
			}//HALFFLAG F END OF IF

			else if(HalfFlag == true){//HALFFLAG T IF
				HalfFlag = false;
			}//HALFFLAG T END OF IF

		}//XBUTTON END OF IF
		if(YButton){//YBUTTON IF
			if(RevDrive){//REVDRIVE T IF
			RevDrive = false;
			}//REVDRIVE T END OF IF
			else{//REVDRIVE F IF
				RevDrive = true;
			}//REVDRIVE F END OF IF
		}//YBUTTON END OF IF
		if(RevDrive == false){//DRIVE REVDRIVE F IF
			if(HalfFlag == false){//DRIVE HALFFLAG F END OF IF
				Robot::driveSub->MecanumDrive(XAxis,-YAxis, RotAxis, 0);
			}//DRIVE HALFFLAG F END OF IF
			else{//DRIVE HALFFLAG T IF
				Robot::driveSub->HalfSpeed(XAxis,-YAxis,RotAxis,0);
			}//DRIVE HALFFLAG T END OF IF
		}//DRIVE REVDRIVE F END OF IF

		else if(RevDrive == true){//DRIVE REVDRIVE T IF
			if(HalfFlag == false){//DRIVE HALFFLAG F END OF IF
				Robot::driveSub->MecanumDrive(-XAxis,-YAxis, RotAxis, 0);
			}//DRIVE HALFFLAG F END OF IF
			else{//DRIVE HALFFLAG T IF
				Robot::driveSub->HalfSpeed(-XAxis,-YAxis,RotAxis,0);
			}//DRIVE HALFFLAG T END OF IF
		}//DRIVE REVDRIVE END OF IF
}

// Make this return true when this Command no longer needs to run execute()
bool DriveCom::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveCom::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveCom::Interrupted() {

}
